spring.profiles.active=${PROFILE:local}

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.username=root
spring.datasource.password=Root12345!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
keycloak.auth-server-url=http://localhost:8070/
keycloak.realm=master

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8070/realms/master/protocol/openid-connect/certs

#aceasta este o proprietate in plus, care specifica dialectul limbajului SQL
#fiecare baza de date foloseste limbajul SQL, dar cu un dialect diferit (difera cateva mici elemente de sintaxa)
#prin aceasta proprietate ii spunem framework-ului sa foloseasca dialectul de MySQL pentru a interactiona cu baza de date)
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

